# -*- coding: utf-8 -*-
"""31-01-23/Machine_Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AGptFafManXJcSflC6WHibXvu6vt6qg9
"""

import pandas as pd
from matplotlib import pyplot as plt

df = pd.read_csv('/content/Salary_Data.csv')

df.head()

plt.scatter(df.YearsExperience, df.Salary, color='blue')
plt.xlabel("YearsExperience")
plt.ylabel("Salary")
plt.show()

from sklearn.linear_model import LinearRegression

lm = LinearRegression()
lm

x = df[['YearsExperience']]
y = df['Salary']

lm.fit(x,y)

T = [[2]]
Yhat = lm.predict(x)
Yhat

lm.intercept_

lm.coef_

from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y,Yhat)
print('The mean squared error of price and predict value is: ',mse )

lm.score(x,y)

